"""initial_migration

Revision ID: 8e9f118c0ab3
Revises: 
Create Date: 2026-08-23 15:07:58.762696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e9f118c0ab3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('barcode', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('manufacturer', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_barcode'), ['barcode'], unique=True)
        batch_op.create_index(batch_op.f('ix_products_product_name'), ['product_name'], unique=False)

    op.create_table('rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rule_id', sa.String(length=100), nullable=False),
    sa.Column('rule_number', sa.String(length=100), nullable=True),
    sa.Column('rule_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('requirement', sa.Text(), nullable=True),
    sa.Column('validation_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rules_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_rules_rule_id'), ['rule_id'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'INSPECTOR', 'VIEWER', name='user_role_enum', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('inspections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('inspector_id', sa.Integer(), nullable=False),
    sa.Column('inspection_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='inspection_status_enum', native_enum=False), nullable=False),
    sa.Column('compliance_score', sa.Float(), nullable=True),
    sa.Column('overall_result', sa.Enum('PENDING', 'COMPLIANT', 'NON_COMPLIANT', 'WARNING', name='compliance_result_enum', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['inspector_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inspections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inspections_inspector_id'), ['inspector_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspections_product_id'), ['product_id'], unique=False)

    op.create_table('declarations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('declaration_type', sa.String(length=100), nullable=False),
    sa.Column('extracted_value', sa.Text(), nullable=True),
    sa.Column('normalized_value', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source_image', sa.String(length=500), nullable=True),
    sa.Column('bounding_box', sa.JSON(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('declarations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_declarations_declaration_type'), ['declaration_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_declarations_inspection_id'), ['inspection_id'], unique=False)

    op.create_table('inspection_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inspection_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inspection_images_inspection_id'), ['inspection_id'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('report_path', sa.String(length=500), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_inspection_id'), ['inspection_id'], unique=True)

    op.create_table('violations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.String(length=100), nullable=False),
    sa.Column('violation_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO', name='violation_severity_enum', native_enum=False), nullable=False),
    sa.Column('evidence_image', sa.String(length=500), nullable=True),
    sa.Column('detected_value', sa.Text(), nullable=True),
    sa.Column('expected_value', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'RESOLVED', 'DISMISSED', name='violation_status_enum', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('violations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_violations_inspection_id'), ['inspection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_violations_rule_id'), ['rule_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('violations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_violations_rule_id'))
        batch_op.drop_index(batch_op.f('ix_violations_inspection_id'))

    op.drop_table('violations')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_inspection_id'))

    op.drop_table('reports')
    with op.batch_alter_table('inspection_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inspection_images_inspection_id'))

    op.drop_table('inspection_images')
    with op.batch_alter_table('declarations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_declarations_inspection_id'))
        batch_op.drop_index(batch_op.f('ix_declarations_declaration_type'))

    op.drop_table('declarations')
    with op.batch_alter_table('inspections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inspections_product_id'))
        batch_op.drop_index(batch_op.f('ix_inspections_inspector_id'))

    op.drop_table('inspections')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rules_rule_id'))
        batch_op.drop_index(batch_op.f('ix_rules_category'))

    op.drop_table('rules')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_product_name'))
        batch_op.drop_index(batch_op.f('ix_products_barcode'))

    op.drop_table('products')
    # ### end Alembic commands ###
