import jsPDF from "jspdf";

const PAGE_WIDTH = 210;
const PAGE_HEIGHT = 297;
const MARGIN = 18;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;

function formatValue(value) {
  if (value === null || value === undefined || value === "") {
    return "Not available";
  }

  return String(value);
}

function formatDate(value) {
  if (!value) return "Not available";

  const date = new Date(value);

  if (Number.isNaN(date.getTime())) {
    return String(value);
  }

  return date.toLocaleString("en-IN", {
    dateStyle: "medium",
    timeStyle: "short",
  });
}

function addFooter(doc, pageNumber) {
  const totalPages = doc.getNumberOfPages();

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(100, 100, 100);

  doc.text(
    "Generated by Nirikshak — Prototype System",
    MARGIN,
    PAGE_HEIGHT - 10
  );

  doc.text(
    `Page ${pageNumber} of ${totalPages}`,
    PAGE_WIDTH - MARGIN,
    PAGE_HEIGHT - 10,
    { align: "right" }
  );
}

function checkPageSpace(doc, currentY, requiredHeight = 20) {
  if (currentY + requiredHeight > PAGE_HEIGHT - 20) {
    doc.addPage();
    return MARGIN;
  }

  return currentY;
}

function addSectionTitle(doc, title, y) {
  y = checkPageSpace(doc, y, 15);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(30, 41, 59);
  doc.text(title, MARGIN, y);

  return y + 8;
}

function addLabelValue(doc, label, value, y) {
  y = checkPageSpace(doc, y, 10);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(51, 65, 85);
  doc.text(`${label}:`, MARGIN, y);

  doc.setFont("helvetica", "normal");
  doc.setTextColor(71, 85, 105);

  const labelWidth = 42;
  const valueLines = doc.splitTextToSize(
    formatValue(value),
    CONTENT_WIDTH - labelWidth
  );

  doc.text(valueLines, MARGIN + labelWidth, y);

  return y + Math.max(7, valueLines.length * 5 + 2);
}

function addProductDetails(doc, product, y) {
  const fields = [
    ["Product Name", product?.product_name],
    ["Manufacturer", product?.manufacturer],
    ["Net Quantity", product?.net_quantity],
    ["MRP", product?.mrp],
    ["Batch Number", product?.batch_number],
    ["Mfg Date", product?.mfg_date],
    ["Consumer Care", product?.consumer_care],
  ];

  fields.forEach(([label, value]) => {
    y = addLabelValue(doc, label, value, y);
  });

  return y;
}

function addViolations(doc, violations, y) {
  if (!violations || violations.length === 0) {
    y = checkPageSpace(doc, y, 12);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(71, 85, 105);
    doc.text("No violations detected.", MARGIN, y);

    return y + 8;
  }

  violations.forEach((violation, index) => {
    y = checkPageSpace(doc, y, 35);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(51, 65, 85);

    doc.text(
      `${index + 1}. ${formatValue(violation?.rule)}`,
      MARGIN,
      y
    );

    y += 6;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(71, 85, 105);

    const descriptionLines = doc.splitTextToSize(
      formatValue(violation?.description),
      CONTENT_WIDTH - 8
    );

    doc.text(descriptionLines, MARGIN + 5, y);

    y += descriptionLines.length * 4.5 + 3;

    if (violation?.field) {
      doc.setFontSize(8);
      doc.setTextColor(100, 116, 139);
      doc.text(
        `Affected field: ${violation.field}`,
        MARGIN + 5,
        y
      );
      y += 6;
    }
  });

  return y;
}

export function generateComplianceReportPDF(scanData, inspectorInfo = {}) {
  if (!scanData) {
    throw new Error("Scan data is required to generate the report.");
  }

  const doc = new jsPDF();

  const product = scanData.product || {};
  const compliance = scanData.compliance || {};
  const violations = compliance.violations || [];

  let y = MARGIN;

  // Header
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(15, 23, 42);

  const titleLines = doc.splitTextToSize(
    "Legal Metrology Compliance Inspection Report",
    CONTENT_WIDTH
  );

  doc.text(titleLines, MARGIN, y);

  y += titleLines.length * 8 + 5;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);

  doc.text(`Scan ID: ${formatValue(scanData.scan_id)}`, MARGIN, y);
  y += 5;

  doc.text(
    `Inspection Date: ${formatDate(scanData.timestamp)}`,
    MARGIN,
    y
  );

  y += 12;

  // Inspector section
  y = addSectionTitle(doc, "Inspector Information", y);

  y = addLabelValue(
    doc,
    "Name",
    inspectorInfo?.full_name || inspectorInfo?.name,
    y
  );

  y = addLabelValue(
    doc,
    "Email",
    inspectorInfo?.email,
    y
  );

  y = addLabelValue(
    doc,
    "Report Generated",
    new Date().toLocaleString("en-IN", {
      dateStyle: "medium",
      timeStyle: "short",
    }),
    y
  );

  y += 4;

  // Product section
  y = addSectionTitle(doc, "Product Details", y);
  y = addProductDetails(doc, product, y);

  y += 5;

  // Compliance verdict
  y = addSectionTitle(doc, "Compliance Verdict", y);

  y = checkPageSpace(doc, y, 25);

  const status = formatValue(compliance.status).toUpperCase();

  let statusColor = [71, 85, 105];

  if (status === "COMPLIANT") {
    statusColor = [22, 163, 74];
  } else if (status === "NON_COMPLIANT") {
    statusColor = [220, 38, 38];
  } else if (status === "PARTIAL") {
    statusColor = [217, 119, 6];
  }

  doc.setFillColor(...statusColor);
  doc.roundedRect(MARGIN, y - 5, CONTENT_WIDTH, 12, 3, 3, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.setTextColor(255, 255, 255);

  doc.text(status, PAGE_WIDTH / 2, y + 3.5, {
    align: "center",
  });

  y += 19;

  // Violations
  y = addSectionTitle(doc, "Rule Violations", y);
  y = addViolations(doc, violations, y);

  // Footer
  const totalPages = doc.getNumberOfPages();

  for (let page = 1; page <= totalPages; page++) {
    doc.setPage(page);
    addFooter(doc, page);
  }

  const scanId = formatValue(scanData.scan_id).replace(
    /[^a-zA-Z0-9-_]/g,
    ""
  );

  doc.save(`Nirikshak-Compliance-Report-${scanId}.pdf`);
}